version: '3'

services:
  app:
    build: .
    image: linyq1/playwright:latest
    user: root
    ports:
      - "8000:8000"
    volumes:
#      - ./cookies:/app/cookies
#      - ./data:/app/data
      - ./:/app/
    env_file:
      - .env
#    command: sleep 24h
    command: sh /app/docker-entrypoint.sh
